apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sockshop-gateway
  namespace: sock-shop
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: front-end-ingress
  namespace: sock-shop
spec:
  hosts:
    - '*'
  gateways:
    - sock-shop/sockshop-gateway
  http:
    - route:
        - destination:
            host: front-end

---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: front-end
  namespace: sock-shop
spec:
  hosts:
    - 'front-end'
  http:
    - match:
      - headers:
          apiVersion:
            exact: v2
      route:
      - destination:
          host: front-end
          subset: v2
    - route:
        - destination:
            host: front-end
            subset: v1
          weight: 100
        - destination:
            host: front-end
            subset: v2
          weight: 0
          
---