---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: carts-db-v1
  labels:
    app: carts-db
    version: v1
  namespace: sock-shop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: carts-db
        version: v1
    spec:
      containers:
      - name: carts-db
        image: mongo
        ports:
        - name: mongo
          containerPort: 27017
        resources:
          limits:
            cpu: 2000m
            memory: 4000Mi
          requests:
            cpu: 800m
            memory: 1000Mi
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux
