---
apiVersion: v1
kind: Service
metadata:
  name: carts
  labels:
    app: carts
    service: carts
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: carts
