---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalogue-db-v1
  labels:
    app: catalogue-db
    version: v1
  namespace: sock-shop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: catalogue-db
        version: v1
    spec:
      containers:
      - name: catalogue-db
        image: weaveworksdemos/catalogue-db:0.3.0
        resources:
          limits:
            cpu: 2000m
            memory: 4000Mi
          requests:
            cpu: 800m
            memory: 1000Mi
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: fake_password
          - name: MYSQL_DATABASE
            value: socksdb
        ports:
        - name: mysql
          containerPort: 3306
      nodeSelector:
        beta.kubernetes.io/os: linux
