---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    app: front-end
    service: front-end
  namespace: sock-shop
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8079
  selector:
    app: front-end
