---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq-v1
  labels:
    app: rabbitmq
    version: v1
  namespace: sock-shop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
        version: v1
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.6.8-management
        ports:
        - containerPort: 15672
          name: management
        - containerPort: 5672
          name: rabbitmq
        - containerPort: 4369
          name: epmd
        - containerPort: 25672
          name: dist
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - SETGID
              - SETUID
              - DAC_OVERRIDE
          readOnlyRootFilesystem: true
      - name: rabbitmq-exporter
        image: kbudde/rabbitmq-exporter
        ports:
        - containerPort: 9090
          name: exporter
      nodeSelector:
        beta.kubernetes.io/os: linux
