---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    service: rabbitmq
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - name: rabbitmq
    port: 5672
    targetPort: rabbitmq
  - name: epmd
    port: 4369
    targetPort: epmd
  - name: management
    port: 15672
    targetPort: management
  - name: dist
    port: 25672
    targetPort: dist
  - port: 9090
    name: exporter
    targetPort: exporter
    protocol: TCP

  selector:
    app: rabbitmq
