---
apiVersion: v1
kind: Service
metadata:
  name: session-db
  labels:
    app: session-db
    service: session-db
  namespace: sock-shop
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
    name: redis
    targetPort: 6379
  selector:
    app: session-db
