---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: payment
  namespace: sock-shop-pure
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: payment-v1

  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
    
